name: pfsmonitor
description: Sistema de monitoramento de sites

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.14.0
  rxdart: ^0.27.3
  validators: ^3.0.0
  bot_toast: ^4.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
